services:
  storage:
      container_name: stor
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      image: postgres:15-alpine
      ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
      command:
        - 'postgres'
        - '-c'
        - 'port=${POSTGRES_PORT}'
      volumes:
        - storage_vol:/var/lib/postgresql/data
      networks:
        - server_net

  api:
    container_name: apigolang
    build: ./apiGolang
    depends_on:
      - storage
    networks:
      - server_net
    ports:
      - ${HTTP_API_PORT}:${HTTP_API_PORT}

volumes: 
  storage_vol: {}

networks:
  server_net:
    driver: bridge


# docker compose --env-file configLocal.env up --build -d



